origin_blacklist_use_simple_whitelist: false
display_ban_type_on_kick: false
server_name: EaglercraftBungee Server
origin_blacklist_subscriptions:
- https://g.lax1dude.net/eaglercraft/origin_blacklist.txt
- https://raw.githubusercontent.com/LAX1DUDE/eaglercraft/main/stable-download/origin_blacklist.txt
token_verify: ''
groups: {}
servers:
  lobby:
    address: 146.59.0.143:25571
    restricted: false
voice_stun_servers:
- stun:openrelay.metered.ca:80
enable_web_origin_blacklist: true
origin_blacklist_simple_whitelist:
- type the name of your client's domain here
- (if 'origin_blacklist_use_simple_whitelist' is true)
- g.lax1dude.net
protocol_support_fix: true
timeout: 30000
listeners:
- request_motd_cache:
    online_server_list_results: true
    online_server_list_trending: true
    cache_ttl: 7200
    online_server_list_animation: false
    online_server_list_portfolios: false
  ratelimit:
    motd:
      period: 30
      lockout_duration: 1200
      enable: true
      limit: 5
      limit_lockout: 15
      exceptions: []
    ip:
      period: 90
      lockout_duration: 1200
      enable: true
      limit: 60
      limit_lockout: 80
      exceptions: []
    query:
      period: 90
      lockout_duration: 1200
      enable: true
      limit: 60
      limit_lockout: 80
      exceptions: []
    login:
      period: 50
      lockout_duration: 300
      enable: true
      limit: 5
      limit_lockout: 10
      exceptions: []
  tab_list: GLOBAL_PING
  texture_size: 16
  allow_query: true
  forced_hosts: {}
  motd1: 'kendev.ct8.pl/eaglercraftserv'
  allow_motd: true
  default_server: lobby
  fallback_server: lobby
  websocket: true
  server_icon: server-icon.png
  forward_ip: false
  host: 0.0.0.0:25565
  max_players: 60
  tab_size: 60
  force_default_server: true
  forward_ip_header: X-Real-IP
  java_host: 'null'
origin_blacklist_block_invalid_origin_header: true
voice_enabled: true
player_limit: -1
origin_blacklist_block_offline_download: false
accept_bukkit_console_command_packets: false
authservice:
  authfile: auths.db
  register_enabled: true
  ip_limit: 0
  join_messages:
  - '&3Welcome to my &aEaglercraftBungee &3server!'
  login_timeout: 30
  enabled: false
disabled_commands: []
bungee_on_bungee: false
origin_blacklist_block_replit_clients: false
stats: d849a096-98a5-468b-be48-c41df4d33386
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.eag.domain
  - bungeecord.command.eag.changepassword
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.eag.ban
  - bungeecord.command.eag.banwildcard
  - bungeecord.command.eag.banip
  - bungeecord.command.eag.banregex
  - bungeecord.command.eag.reloadban
  - bungeecord.command.eag.banned
  - bungeecord.command.eag.banlist
  - bungeecord.command.eag.unban
  - bungeecord.command.eag.ratelimit
  - bungeecord.command.eag.blockdomain
  - bungeecord.command.eag.blockdomainname
  - bungeecord.command.eag.unblockdomain
voice_turn_servers:
  openrelay3:
    password: openrelayproject
    url: turn:openrelay.metered.ca:443?transport=tcp
    username: openrelayproject
  openrelay2:
    password: openrelayproject
    url: turn:openrelay.metered.ca:443
    username: openrelayproject
  openrelay1:
    password: openrelayproject
    url: turn:openrelay.metered.ca:80
    username: openrelayproject
